raw_text: |
  Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

  ### Instruction:
  Given the question and answer provided after this instruction, show the logic behind the solution through chain of thought reasoning.

  In case you are not familiar, chain of thought reasoning involves detailing the logical steps taken to arrive at a conclusion. This` approach not only provides an outcome but also illuminates the process of reasoning used.

  ### Input:
  #### Question:
  {question}
  #### Supporting Information:
  {supporting_information}
  #### Answer:
  {answer}

  ### Response:
  #### Chain of Thought:

dataset_supplied_inputs_map:
  question: question
  support: supporting_information
  correct_answer: answer

user_supplied_inputs: [user_supplied_suffix]

default_dataset_name: "sciq"

output_format: "raw_completion"
